# Generated by Django 2.2.13 on 2020-09-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('actor', models.EmailField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=50)),
                ('release_date', models.DateField(verbose_name='Release_Date')),
            ],
        ),
    ]
