# Generated by Django 2.2.13 on 2020-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating', '0002_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.URLField(default='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
